[23기 임종성] Modify S3Client Class
wecode-bootcamp-korea/23-2nd-OURSPACE-backend pull request #11
Opened 2021-08-25 16:46 UTC by Jongseong0111

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- S3Client 수정
- ReviewView, HotsPostView 수정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

- S3에 업로드된 파일 삭제하는 함수 추가, 소멸자 추가
- ReviewView, HostPostView에서 이미지 등록시 DB에 저장되는 파일경로와 S3 파일경로 다른 에러 수정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-25 16:54 UTC, Jongseong0111 commented
S3Client Class를 손보려고 테스트하는 중, Review를 생성하면서 uuid를 쓰고 S3에 업로드하면서 또 uuid를 사용해서 결과적으로 db에 저장된 경로와 s3의 파일경로가 다른것을 확인했습니다. 그래서 S3Client 함수를 수정하고 동일한 경로가 저장될 수 있도록 했습니다.

2021-08-26 04:57 UTC, Kang-kyunghun requested changes

2021-08-26 04:57 UTC, Kang-kyunghun commented on ourspace/settings.py
> +
sql 로깅 관련한 코드는 실세 서비스에서는 성능을 많이 저하 시키므로 깃허브에서는 제거해 주세요.

2021-08-26 04:58 UTC, Kang-kyunghun requested changes

2021-08-26 04:58 UTC, Kang-kyunghun commented on orders/views.py
> +    @query_debugger
실제 코드에서는 디버거 모드는 제거해 주세요.

2021-08-26 04:58 UTC, Kang-kyunghun commented on spaces/views.py
> +    @query_debugger
여기도 제거해 주세요.

2021-08-26 06:25 UTC, Jongseong0111 commented on spaces/views.py
> +    @query_debugger
모두 수정 완료했습니다!

2021-08-26 06:26 UTC, Kang-kyunghun commented
LGTM~~!

2021-08-26 06:26 UTC, merged