[23기 임종성]PageView With UnitTest
wecode-bootcamp-korea/23-2nd-OURSPACE-backend pull request #3
Opened 2021-08-19 09:54 UTC by Jongseong0111

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 여러 종류의 필터링 적용하는 페이지 View
- 이미지 파일을 저장하기 위해 S3 사용, setting에 추가
- 3종류 Unit Test 성공(카테고리와 지역별, Date별, Order별) 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-19 10:14 UTC, Jongseong0111 commented
test.py 컨벤션 하겠습니다!

2021-08-20 01:30 UTC, Jongseong0111 commented
> test.py 컨벤션 하겠습니다!

수정 완료했습니다.

2021-08-20 01:33 UTC, Kang-kyunghun requested changes

2021-08-20 01:33 UTC, Kang-kyunghun commented on spaces/views.py
> +class MenuPageView(View):
```suggestion
class ProductsView(View):
```
저희는 페이지 단위가 아닌 자원 단위로 생각해야 합니다. 해당 API가 무조건 mainpage에서만 사용되는 것이 아니고, 다른 곳에서도 충분히 사용될 수 있습니다.

2021-08-20 01:33 UTC, Kang-kyunghun commented on spaces/views.py
> +        mancount    = request.GET.get('count', None)
```suggestion
        man_count    = request.GET.get('count', None)
```

2021-08-20 01:33 UTC, Kang-kyunghun commented on spaces/views.py
> +            q &= Q(min_count__lte = mancount) & Q(max_count__gte = mancount)
__range 라는 것도 있습니다. 한 번 찾아보세요~

2021-08-20 01:33 UTC, Kang-kyunghun commented on spaces/views.py
> +                } for district in District.objects.all()],
매번 district 정보를 다 주는 이유를 남겨주세요.

2021-08-20 01:33 UTC, Kang-kyunghun commented on spaces/views.py
> +            q &= ~Q(id__in=booked_id)
이 부분은 만나서 한 번 이야기 해봐요

2021-08-20 01:41 UTC, Jongseong0111 commented on spaces/views.py
> +                } for district in District.objects.all()],
메뉴페이지를 표출할 경우 프론트엔드쪽에서 District에 대한 정보가 필요해서 넘겨주었습니다! 
지도 API를 진행할 경우 지역 기준 위도, 경도가 필요하기에 같이 보냈습니다.

2021-08-20 01:42 UTC, Jongseong0111 commented on spaces/views.py
> +            q &= ~Q(id__in=booked_id)
네 알겠습니다!

2021-08-20 08:25 UTC, Jongseong0111 commented on spaces/views.py
> +                } for district in District.objects.all()],
District View 분리하고 Unit Test 완료했습니다.

2021-08-20 10:13 UTC, Jongseong0111 commented on spaces/views.py
> +            q &= ~Q(id__in=booked_id)
수정사항 반영해서 push 올렸습니다~

2021-08-21 06:31 UTC, Jongseong0111 commented
select_related, prefetch_related 사용해서 총 Query 호출을 100번에서 3번으로 줄였습니다.

2021-08-23 02:24 UTC, Kang-kyunghun reviewed
> select_related, prefetch_related 사용해서 총 Query 호출을 100번에서 3번으로 줄였습니다.
> 그런데 QuerySet을 선언하는 코드는 많이 길어져서 이래도 괜찮은가 싶습니다.
 
코드의 길이가 길어지면 가독성이 나빠지기 때문에 안 좋을 수 있습니다. 지금과 같은 상황은 다 필요한 구문들로 보입니다. 불가피하게 길어질 경우 .을 기준으로 정렬한다든지 해서 가독성을 높여주면 좋을 것 같아요.

2021-08-23 02:24 UTC, Kang-kyunghun commented on spaces/views.py
> +                } for district in District.objects.all()],
그렇다면 api를 따로 분리해 주세요.

2021-08-23 02:24 UTC, Kang-kyunghun commented
LGTM~!

2021-08-23 02:24 UTC, merged