[23기 임종성]OrderView
wecode-bootcamp-korea/23-2nd-OURSPACE-backend pull request #5
Opened 2021-08-22 16:41 UTC by Jongseong0111

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

- Order Post 기능 구현
- 가상 Token 발급하여 Unit Test 2개의 Case 통과(Key Error, Success)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-23 01:56 UTC, Kang-kyunghun requested changes

2021-08-23 01:56 UTC, Kang-kyunghun commented on orders/views.py
> +                Order.objects.filter(user_id = request.user.id, status_id = OrderStatus.Status.WAITING.value).delete()
기존에 예약한 공간이 있으면 지우고 다시 예약하는 건가요?

2021-08-23 01:56 UTC, Kang-kyunghun commented on orders/views.py
> +                option    = Option.objects.get(space_id = space_id, option=data['option']),
option_id의 존재 유무를 판단 후에 get 대신에 option_id를 직접 넣어줘도 될 것 같아요.
```suggestion
                option_id    = data['option'],
```

2021-08-23 02:45 UTC, Jongseong0111 commented on orders/views.py
> +                Order.objects.filter(user_id = request.user.id, status_id = OrderStatus.Status.WAITING.value).delete()
status = waiting인 경우는 결제페이지에서 결제 전에 정보를 보여주기 위해 설정해 놓은 상태이고
상세페이지에서 예약을 누르면 waiting으로 생성,
결제 페이지에서 결제를 누르면 completed로 바뀝니다.
그래서 각 user마다 order의 status가 waiting인 data는 1개만 있어야 하기때문에 지워주었습니다.

2021-08-23 06:25 UTC, Jongseong0111 commented on orders/views.py
> +                option    = Option.objects.get(space_id = space_id, option=data['option']),
option_id를 받기로 했습니다!

2021-08-23 07:43 UTC, Jongseong0111 commented on orders/views.py
> +                option    = Option.objects.get(space_id = space_id, option=data['option']),
예약 관련 GET Method까지 추가하여 올렸습니다!

2021-08-23 08:11 UTC, Kang-kyunghun requested changes

2021-08-23 08:11 UTC, Kang-kyunghun commented on orders/views.py
> +                Order.objects.filter(user_id = request.user.id, status_id = OrderStatus.Status.WAITING.value).delete()
👍

2021-08-23 08:11 UTC, Kang-kyunghun commented on orders/views.py
> +        order = Order.objects.select_related('space').get(user_id = 2, status_id = OrderStatus.Status.WAITING.value)
user_id가 하드코딩 되어 있네요. 수정해 주세요.

2021-08-23 08:11 UTC, Kang-kyunghun commented on orders/tests.py
> +class OrderPostViewTest(TestCase):
View이름이 바뀐 것 같은데, 그럼 여기도 바껴야 되겠죠?

2021-08-23 08:43 UTC, Jongseong0111 commented on orders/views.py
> +        order = Order.objects.select_related('space').get(user_id = 2, status_id = OrderStatus.Status.WAITING.value)
test 하다가 수정못했던 것 같습니다. 수정했습니다!

2021-08-23 08:45 UTC, Jongseong0111 commented on orders/tests.py
> +class OrderPostViewTest(TestCase):
모두 Reserve로 변경했습니다!

2021-08-23 08:46 UTC, Jongseong0111 commented
말씀해주신 SimpleUploadedFile로 Unit Test 적용했습니다!

2021-08-23 11:04 UTC, Kang-kyunghun requested changes

2021-08-23 11:04 UTC, Kang-kyunghun commented on orders/tests.py
> +                image    =  SimpleUploadedFile('Image1', b"Image Content")
이미지 필드 전부 URL필드로 바꾼다고 들은 것 같은데, 그렇게 되면 test를 전체적으로 수정해야 할 것 같습니다.
SimpleUplodaFile은 이미지를 등록하는 api에서 실제로 이미지를 전송하는 것 대신에 사용하면 됩니다.
test에서 이미지를 생성하는 부분들은 URL 필드로 바꾼뒤에 링크를 str로 넣어 주시면 될 것 같아요.

2021-08-23 16:05 UTC, Jongseong0111 commented on orders/tests.py
> +                image    =  SimpleUploadedFile('Image1', b"Image Content")
Imag를 모두 URL로 바꾸면서 unit test와 View 모두 조금씩 수정하였습니다!

2021-08-24 01:14 UTC, Kang-kyunghun commented
LGTM

2021-08-24 01:14 UTC, merged