[23기 장이주]공간등록 기능 구현
wecode-bootcamp-korea/23-2nd-OURSPACE-backend pull request #6
Opened 2021-08-22 18:12 UTC by Jang184

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 공간 등록 기능 구현
		 
## 수정 사항들 자세한 내용
- 공간 등록 성공시 'success' 메세지 반환
- s3 이미지 호스팅 경로 변경
- 토큰 key값 변경

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-23 01:53 UTC, Kang-kyunghun requested changes

2021-08-23 01:53 UTC, Kang-kyunghun commented on spaces/views.py
> +class HostPostView(View):
```suggestion
class HostView(View):
```
host 자원과 관련된 다른 method들도 추가 될 수 있습니다. View이름을 지을 때는 어떤 자원을 활용할 건지 고려해서 지으시고, 행동과 관련해서는 method로 표현해 주시면 될 것 같습니다.

2021-08-23 01:53 UTC, Kang-kyunghun commented on spaces/views.py
> +        images     = request.FILES.getlist('image')
이미지 같은 경우 파일을 직접 DB에 저장하는 것이 아니고, S3같은 클라우드 서비에서 저장 후 저장한 곳의 URL을 DB에 저장해 주셔야 합니다.

2021-08-23 01:53 UTC, Kang-kyunghun commented on spaces/views.py
> +        try:
공간을 등록하기 위해서 지금 여러 테이블들이 관여하고 있는데, transection에 대해서 알아보고 한 번 적용해 보세요.

2021-08-23 02:41 UTC, Jongseong0111 commented on spaces/views.py
> +        images     = request.FILES.getlist('image')
파일은 S3에 저장하고 경로만 db에 저장하게 세팅했다고 생각했는데 잘못된 부분이 있나요??

2021-08-23 05:45 UTC, Jang184 commented on spaces/views.py
> +        images     = request.FILES.getlist('image')
이미지필드에서 URL필드로 수정중입니다! 수정완료 후 다시 pr올리겟습니당~

2021-08-24 01:09 UTC, Kang-kyunghun requested changes

2021-08-24 01:09 UTC, Kang-kyunghun commented on spaces/views.py
> +                    like        = 0
- district_id가 하드 코딩 되어 있습니다.
- min_count와 like는 default 값을 주어서 create 할 때 하드코딩 안 되게 하면 좋을 것 같습니다.

2021-08-24 02:56 UTC, Jang184 commented on spaces/views.py
> +                    like        = 0
수정 하였습니다~!

2021-08-24 08:09 UTC, Kang-kyunghun commented
LGTM~!

2021-08-24 08:09 UTC, merged