[23기 임종성] ReviewView
wecode-bootcamp-korea/23-2nd-OURSPACE-backend pull request #9
Opened 2021-08-24 05:04 UTC by Jongseong0111

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 리뷰 작성 기능, Unit Test 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-24 08:13 UTC, Kang-kyunghun requested changes

2021-08-24 08:13 UTC, Kang-kyunghun commented on spaces/views.py
> +    )
이주님도 s3를 사용하고 있는데, 공통으로 사용되는 s3 부분을 공통 클라우드로 만들어서 관리해 보세요.

2021-08-24 08:13 UTC, Kang-kyunghun commented on spaces/views.py
> +                )
```suggestion
                    user     = request.user,
                    space_id = space_id,
                    image    = 'https://ourspace-js.s3.ap-northeast-2.amazonaws.com/static/review/' + key,
                    grade    = data['grade'],
                    content  = data['content']
                )
```

2021-08-25 00:48 UTC, Kang-kyunghun requested changes

2021-08-25 00:48 UTC, Kang-kyunghun commented on spaces/urls.py
> +<<<<<<< HEAD
conflict 해결이 잘 안 되었네요.

2021-08-25 00:48 UTC, Kang-kyunghun commented on spaces/tests.py
> +    @patch('spaces.views.boto3.client')
혹시 s3 class 만든 후에 test 돌려 보셨나요? test 결과도 첨부해 주세요.

2021-08-25 02:45 UTC, Jongseong0111 commented on spaces/tests.py
> +    @patch('spaces.views.boto3.client')
![image](https://user-images.githubusercontent.com/84963683/130717942-1a96368f-9c7c-4670-b046-b681b8ffdb30.png)
Unit Test 완료되었습니다!

2021-08-25 05:11 UTC, Kang-kyunghun commented
LGTM~~~!!

2021-08-25 05:11 UTC, merged